# Generated by Django 5.2.1 on 2025-05-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido')], default='emprestado', max_length=20),
        ),
    ]
